config/routes.rb
Rails.application.routes.draw do
  resources :login
  resources :reclamacaos
  resources :usuarios
  get 'login/index'
  root "reclamacaos#index"
  get 'login/destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reclamacao.rb
class Reclamacao < ApplicationRecord
  belongs_to :usuario
  validates :titulo, presence: {message: "campo obrigatório"}, format: {with: /[A-Za-z0-9]+/}, length: {minimum: 5, too_short: "%{count} caracteres é o minimo permitido ", maximum:20, too_long: "%{count} caracteres é o máximo permitido " }, uniqueness: true
  validates :cat_problema, presence: {message: "campo obrigatório"}, length: {minimum: 5 , too_short: "%{count} caracteres é o minimo permitido ", maximum:20, too_long: "%{count} caracteres é o máximo permitido " }
  validates :texto, presence: {message: "campo obrigatório"}, format: {with: /[A-Za-z0-9]+/}, length: {minimum: 5, too_short: "%{count} caracteres é o minimo permitido ", maximum:500, too_long: "%{count} caracteres é o máximo permitido " }
  validates :nome_empresa, presence: {message: "campo obrigatório"},  length: {minimum: 3, too_short: "%{count} caracteres é o minimo permitido ", maximum:20, too_long: "%{count} caracteres é o máximo permitido " }
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  has_many :reclamacaos
  validates :login, presence: {message: 'login inválido!' } , uniqueness: true, length: {minimum:5}
  validates :senha, presence: {message: 'senha inválida!' }, length:{minimum: 5}
  validates :email, presence: {message: 'email inválido!' }, uniqueness: true, length:{minimum: 5}

  private
    @usuario_logado = nil
    @ativo = false

  def self.get_usuario_logado
    @usuario_logado
  end

  def self.set_usuario_logado (usuario)
    @usuario_logado = usuario

    if @usuario_logado != nil
      @ativo = true
    else
      @ativo = false
    end
  end

  def self.logado
    @ativo
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
    @mensagens = []
  end

  def create
    email = params[:email]
    senha = params[:senha]
    usuario = login(email, senha)

    if usuario.nil?
      x = ["EMAIL OU SENHA INCORRETA"]
      @mensagens = x
      render 'login/index'
    else
      Usuario.set_usuario_logado(usuario)
      redirect_to root_path, notice: "LOGIN EFETUADO COM SUCESSO! "
    end
  end

  def login(email, senha)
    usuario = Usuario.all
    user = nil
    usuario.each do |u|
      if u.email == email and u.senha == senha
        user = u
      end
    end
    user
  end

  def destroy
    Usuario.set_usuario_logado(nil)
    redirect_to root_path, notice: "LOGOUT EFETUADO COM SUCESSO! "
  end
end

app/controllers/reclamacaos_controller.rb
class ReclamacaosController < ApplicationController
  before_action :set_reclamacao, only: [:show, :edit, :update, :destroy]

  # GET /reclamacaos
  # GET /reclamacaos.json
  def index
    if params[:title] and params[:empresa]
      @reclamacaos = Reclamacao.where("titulo like ?","%#{params[:title]}%").where(:nome_empresa => params[:empresa])
    else
      @reclamacaos = Reclamacao.all
    end
  end

  # GET /reclamacaos/1
  # GET /reclamacaos/1.json
  def show
  end

  # GET /reclamacaos/new
  def new
    @reclamacao = Reclamacao.new
  end

  # GET /reclamacaos/1/edit
  def edit
    
  end

  # POST /reclamacaos
  # POST /reclamacaos.json
  def create
    @reclamacao = Reclamacao.new(reclamacao_params)
    user = Usuario.get_usuario_logado
    @reclamacao.write_attribute(:usuario_id, user.id)
    respond_to do |format|
      if @reclamacao.save
        format.html { redirect_to root_path, notice: 'RECLAMAÇÃO EFETUADA COM SUCESSO' }
        format.json { render :show, status: :created, location: @reclamacao }
      else
        format.html { render :new }
        format.json { render json: @reclamacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reclamacaos/1
  # PATCH/PUT /reclamacaos/1.json
  def update
    respond_to do |format|
      if @reclamacao.update(reclamacao_params)
        format.html { redirect_to usuario_path(Usuario.get_usuario_logado), notice: 'RECLAMAÇÃO ATUALIZADA!' }
        format.json { render :show, status: :ok, location: @reclamacao }
      else
        format.html { render :edit }
        format.json { render json: @reclamacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reclamacaos/1
  # DELETE /reclamacaos/1.json
  def destroy
    @reclamacao.destroy
    respond_to do |format|
      format.html { redirect_to usuario_path(Usuario.get_usuario_logado), notice: 'RECLAMAÇÃO APAGADA! ' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reclamacao
      @reclamacao = Reclamacao.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reclamacao_params
      params.require(:reclamacao).permit(:titulo, :texto, :cat_problema, :nome_empresa)
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to root_path, notice: 'USUARIO CADASTRADO! ' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        Usuario.set_usuario_logado(@usuario)
        format.html { redirect_to @usuario, notice: 'USUARIO ATUALIZADO! ' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'USUARIO DELETADO! ' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def usuario_params
      params.require(:usuario).permit(:login, :email, :senha)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/reclamacaos_helper.rb
module ReclamacaosHelper
end

app/helpers/sistema_helper.rb
module SistemaHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <body>
    <div id = "principal">
      <header id="header">
        <h2 id="titulo"><span class="reclame">RECLAME</span> <span class="aqui">AQUI!</span></h2><br/>

        <div id="cadastro-login">
          <% if Usuario.logado %>
            <% @usuario = Usuario.get_usuario_logado %>

            <%= link_to 'Nova reclamação', new_reclamacao_path, :class => "bt-consulta"  %>
            <%= link_to "#{@usuario.login}", usuario_path(@usuario), :class => "lc", :id => "usuariologado"%>
            <%= link_to 'logout', login_destroy_path, method: :delete, :class => "lc"  %>
          <% end %>

          <%= link_to " LOGIN " , login_index_path,:class => "lc" %> <br><br> <%= link_to " INSCREVER-SE ", new_usuario_path ,:class => "lc" %> <br/>
        </div>

      </header>
      <br/>

      <%= yield %>

      <br/>
    </div>
  </body>
</html>

app/views/login/index.html.erb
<% if @mensagens.length >= 1 %>
  <% @mensagens.each do |mensagem| %>
    <p class="erro"><%= mensagem %></p>
  <% end %>
<% end %>

<h1>Login</h1><br/>
<%= form_with scope: :login, url:login_index_path , local: true do  %>
  <div class="form-group">
    <%= label_tag 'Email' %>
    <%= text_field_tag  :email, nil, placeholder: "Informe seu email.", :class => "busca-log", :id => "emaillogin" %>
  </div>

  <div class="form-group">
    <%= label_tag 'Senha' %>
    <%= text_field_tag :senha, nil, type: "password", placeholder: "Informe sua senha.", :class => "busca-log", :id => "senhalogin" %>
  </div>

  <div class="actions" id="submit">
    <%= submit_tag 'entrar' %>
  </div>
<% end %>
<br/>
<%= link_to 'voltar', root_path, :class => "btn btn-dark" %>

app/views/reclamacaos/_form.html.erb
<p id="notice"><%= notice %></p>

<div class="formulario-tabela">
  <%= form_with(model: reclamacao, local: true) do |form| %>
    <% if reclamacao.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(reclamacao.errors.count, "error") %> proibiu este reclamação de ser salvo:</h2>

        <ul>
          <% reclamacao.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :titulo %>
      <%= form.text_field :titulo, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :texto %>
      <%= form.text_area :texto, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label 'categoria do problema' %>
      <%= form.text_field :cat_problema, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label 'nome da empresa' %>
      <%= select('reclamacao', :nome_empresa, ['Empresa1','Empresa2','Empresa3'],{include: true}, :class => "form-control") %>
    </div>

    <div class="form-group">
      <%= form.submit 'salvar' %>
    </div>
  <% end %>
</div>

app/views/reclamacaos/edit.html.erb
<h1>Editar Reclamação</h1>

<%= render 'form', reclamacao: @reclamacao %><br/><br/>

<%= link_to 'Voltar', usuario_path,:class => "btn btn-dark" %>

app/views/reclamacaos/index.html.erb
<p id="notice"><%= notice %></p>

<h6><p>Faça o login para cadastrar uma reclamação! </p></h6>

<h6><p> BUSQUE UMA RECLAMAÇÃO PELO TÍTULO </p>
</p></h6>

<%= form_tag(reclamacaos_path, :method =>:get) do %>
  <%=text_field_tag('title', nil, :placeholder => "Titulo da Reclamação", :class => "busca-login") %>
  <%= select_tag 'empresa', raw("<option>Empresa1</option><option>Empresa2</option><option>Empresa3</option>"),{include: true}  %>
  <%= submit_tag "buscar" %>
<% end %>
<br/>

<h2>Reclamações</h2>

<div class="formulario-tabela">
  <table class="table table-striped">
    <thead>
      <tr>
        <th> Titulo </th>
        <th> Texto </th>
        <th> Categoria da reclamação </th>
        <th> Nome da empresa </th>
        <th> Usuario </th>
        <th colspan="6"></th>
      </tr>
    </thead>

    <tbody>
      <% @reclamacaos.each do |reclamacao| %>
        <tr>
          <td><%= reclamacao.titulo %></td>
          <td><%= reclamacao.texto %></td>
          <td><%= reclamacao.cat_problema %></td>
          <td><%= reclamacao.nome_empresa %></td>
          <td><%= reclamacao.usuario.login %></td>
          <td><%= link_to 'Show', reclamacao %></td>
          <td><%= link_to 'Editar', edit_reclamacao_path(reclamacao), id:"e-#{reclamacao.titulo}" %></td>
          <td><%= link_to 'Destroy', reclamacao, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<div/>
<br>
<br/>

app/views/reclamacaos/new.html.erb
<p id = "notice"><%= notice %></p>
<h1>Nova Reclamação</h1>
<%= render 'form', reclamacao: @reclamacao %><br/><br/>

<%= link_to 'voltar', root_path,:class => "btn btn-dark" %>

app/views/reclamacaos/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Reclamação</h1><br/><br/>

<p>
  <strong> Titulo: </strong>
  <%= @reclamacao.titulo %>
</p>

<p>
  <strong> Texto: </strong>
  <%= @reclamacao.texto %>
</p>

<p>
  <strong> Categoria da reclamação: </strong>
  <%= @reclamacao.cat_problema %>
</p>

<p>
  <strong> Nome da empresa: </strong>
  <%= @reclamacao.nome_empresa %>
</p>

<p>
  <strong> Usuario: </strong>
  <%= @reclamacao.usuario.login%>
</p>
<br/><br/>

<%= link_to 'voltar', reclamacaos_path,:class => "btn btn-dark" %>

app/views/usuarios/_form.html.erb
<div class="formulario-tabela">
  <%= form_with(model: usuario, local: true) do |form| %>
    <% if usuario.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(usuario.errors.count, "error") %> proibiu este usuário de ser salvo:</h2>

        <ul>
          <% usuario.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :login %>
      <%= form.text_field :login, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :email %>
      <%= form.text_field :email, :placeholder => "Email deve conter '@'. (ex.: joao@mail)", :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :senha %>
      <%= form.text_field :senha, :placeholder => "Senha com 6 dígitos.", :class => "form-control"%>
    </div>

    <div class="form-group" id="submit">
      <%= form.submit 'salvar'%>
    </div>
  <% end %>
</div>

app/views/usuarios/edit.html.erb
<h2>Editar Usuário</h2>

<%= render 'form', usuario: @usuario %><br/>

<%= link_to 'voltar', @usuario, :class => "btn btn-dark" %>

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Usuários</h2>
<br/><br/>

<div class="formulario-tabela">
  <table class="table table-striped">
    <thead>
      <tr>
        <th> Login </th>
        <th> Email </th>
        <th> Senha </th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @usuarios.each do |usuario| %>
        <tr>
          <td><%= usuario.login %></td>
          <td><%= usuario.email %></td>
          <td><%= usuario.senha %></td>
          <td><%= link_to 'Show', usuario %></td>
          <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
          <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

<%= link_to 'Novo Usuário', new_usuario_path, :class => "btn btn-dark" %>

app/views/usuarios/new.html.erb
<p id="notice1"><%= notice %></p>
<h1>Novo Usuário</h1>

<%= render 'form', usuario: @usuario %>
<br/><br/>
<%= link_to 'voltar', root_path, :class => "btn btn-dark" %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%=@usuario.login%></h1>
<br/><br/>
<p>
  <strong> Login: </strong>
  <%= @usuario.login %>
</p>

<p>
  <strong> Email: </strong>
  <%= @usuario.email %>
</p>

<p>
  <strong> Senha: </strong>
  <%= @usuario.senha %>
</p>

<%= link_to 'Editar', edit_usuario_path(@usuario), :class => "btn btn-dark" %>
<br/><br/>
<hr/>

<h2>Reclamações de <%= @usuario.login %></h2>

<div class="formulario-tabela">
  <table class="table table-striped">
    <thead>
    <tr>
      <th> Titulo </th>
      <th> Texto </th>
      <th> Cat problema </th>
      <th> Nome empresa </th>
      <th> Usuario </th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @usuario.reclamacaos.each do |reclamacao| %>
      <tr>
        <td><%= reclamacao.titulo %></td>
        <td><%= reclamacao.texto %></td>
        <td><%= reclamacao.cat_problema %></td>
        <td><%= reclamacao.nome_empresa %></td>
        <td><%= reclamacao.usuario.login %></td>
        <td><%= link_to 'Ver', reclamacao, :id => "v-#{reclamacao.titulo}" %></td>
        <td><%= link_to 'Editar', edit_reclamacao_path(reclamacao), :id => "e-#{reclamacao.titulo}" %></td>
        <td><%= link_to 'Apagar', reclamacao, method: :delete, data: { confirm: 'Are you sure?' }, :id => "d-#{reclamacao.titulo}" %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<div/>


  <br>

<%= link_to 'voltar', root_path, :class => "btn btn-dark" %>